### ISSUE TITLE
Error in mycoportal_tab: Mycoportal website unavailable (yet can directly download data from Mycoportal)

### ISSUE THREAD

**Issue by cjandrew** [hjsimpso/fungarium#10]
When trying to download as specified in the R help & the manual, cannot download the data (tried across many hours), yet it was downloadable from Mycoportal directly at the same time. 

Could this be an issue with the mycoportal_tab() regarding timing out? Just in case it is anything somehow related to the function, I bring it to your awareness.

>"Error in mycoportal_tab(path.expand("~"), "Pleurotus", taxon_type = "1",  : 
  MyCoPortal website currently unavailable."

>"Error in mycoportal_tab(path.expand("~"), "Pholiota", taxon_type = "1",  : 
  MyCoPortal website currently unavailable.

**Comment by hjsimpso** [comment]
Thanks for the heads up! Looks like it might actually be due to some very recent changes to the layout of the MyCoPortal search page (like within the last 2 weeks). This is the first issue like this I've had since making the function a year ago, which hopefully indicates these type of code-breaking changes won't be frequent. I'll dig a little deeper and make the necessary changes to the function. Thanks again!

**Comment by hjsimpso** [comment]
I've made some changes and `mycoportal_tab` should be working now. Please install the [latest release](https://github.com/hjsimpso/fungarium/releases/tag/v1.1.2) via `install_github("hjsimpso/fungarium@*release")`. If you still have issues please let me know.
